version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  frontend-empresa:
    build:
      context: ./frontend-empresa
    ports:
      - "3002:3000"
    volumes:
      - ./frontend-empresa:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  frontend-personal:
    build:
      context: ./frontend-personal
    ports:
      - "3003:3000"
    volumes:
      - ./frontend-personal:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  admin-empresa:
    build:
      context: ./admin-empresa
    ports:
      - "3004:3000"
    volumes:
      - ./admin-empresa:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  admin-personal:
    build:
      context: ./admin-personal
    ports:
      - "3005:3000"
    volumes:
      - ./admin-personal:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend-empresa
      - frontend-personal
      - admin-empresa
      - admin-personal
    networks:
      - my-network

networks:
  my-network:
    driver: bridge